version: "3.3"
services:
  myblogapi:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblogapp:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    volumes:
      - ./myblog:/app
      - ./myblog/node_modules
    stdin_open: true
    tty: true
